### ISSUE TITLE
FATAL Traject::CommandLine: Unexpected exception, terminating execution: #<NoMethodError: undefined method `source_inspect'

### ISSUE THREAD

**Issue by banukutlu** [psu-libraries/psulib_traject#40]
In GitLab by @cdm32 on Sep 26, 2018, 09:59

On a new laptop, with High Sierra

```
2018-09-26T09:57:39-04:00  INFO    Traject::Indexer with 2 processing threads, reader: Traject::Marc4JReader and writer: Traject::SolrJsonWriter
2018-09-26T09:57:50-04:00 FATAL Traject::CommandLine: Unexpected exception, terminating execution: #<NoMethodError: undefined method `source_inspect' for #<Traject::Indexer::Context:0x7734695d>>
bundler: failed to load command: traject (/Users/cdm32/.rbenv/versions/jruby-9.2.0.0/bin/traject)
NoMethodError: undefined method `source_inspect' for #<Traject::Indexer::Context:0x7734695d>
  /Users/cdm32/.rbenv/versions/jruby-9.2.0.0/lib/ruby/gems/shared/gems/traject-3.0.0.alpha.1/lib/traject/indexer.rb:545:in `block in process'
  /Users/cdm32/.rbenv/versions/jruby-9.2.0.0/lib/ruby/gems/shared/gems/traject-marc4j_reader-1.0.2-java/lib/traject/marc4j_reader.rb:145:in `each'
  /Users/cdm32/.rbenv/versions/jruby-9.2.0.0/lib/ruby/gems/shared/gems/traject-3.0.0.alpha.1/lib/traject/indexer.rb:517:in `block in process'
  org/jruby/RubyArray.java:1801:in `each'
  /Users/cdm32/.rbenv/versions/jruby-9.2.0.0/lib/ruby/gems/shared/gems/traject-3.0.0.alpha.1/lib/traject/indexer.rb:510:in `process'
  /Users/cdm32/.rbenv/versions/jruby-9.2.0.0/lib/ruby/gems/shared/gems/traject-3.0.0.alpha.1/lib/traject/command_line.rb:73:in `execute'
  /Users/cdm32/.rbenv/versions/jruby-9.2.0.0/lib/ruby/gems/shared/gems/traject-3.0.0.alpha.1/bin/traject:14:in `<main>'
  org/jruby/RubyKernel.java:994:in `load'
  /Users/cdm32/.rbenv/versions/jruby-9.2.0.0/bin/traject:1:in `<main>'
  org/jruby/RubyKernel.java:994:in `load'
  /Users/cdm32/.rbenv/versions/jruby-9.2.0.0/bin/traject:23:in `(root)'
```

**Comment by banukutlu** [comment]
In GitLab by @cdm32 on Sep 26, 2018, 10:00

#28

**Comment by banukutlu** [comment]
In GitLab by @cdm32 on Sep 26, 2018, 10:03

i had an out of date repo, plz ignore
